Repository RaeesaParker/neighbourhood-front, pull requests merged in 2022-12, with the labels that each got.

#5 add background and logo img
  src/imgs/Background.png
  src/imgs/logo.svg
Labels: enhancement

#6 Feature main page setup rp
  src/App.js
  src/imgs/Background.png
  src/imgs/logo.svg
  src/pages/mainPage/MainPage.js
  src/pages/mainPage/MainPageStyles.css
Labels: enhancement

#7 Feature nav bar setup rp
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/components/PostsSection/PostsSection.js
  src/components/loginPage/LoginPage.js
  src/components/navigationBar/NavigationBar.js
  src/components/navigationBar/NavigationBarStyles.css
  src/components/sidePanel/SidePanel.js
  src/imgs/Background.png
  src/imgs/logo.svg
  src/index.css
  src/pages/homePage/Homepage.js
  src/pages/mainPage/MainPage.js
  src/pages/mainPage/MainPageStyles.css
  src/pages/userPage/UserPage.js
Labels: enhancement

#8 Mainbody mn
  package-lock.json
  public/index.html
  src/App.css
  src/App.js
  src/components/Feed/Feed.css
  src/components/Feed/Feed.js
  src/components/MainBody/MainBody.css
  src/components/MainBody/MainBody.js
  src/components/NewPost/NewPost.css
  src/components/NewPost/NewPost.js
  src/components/PostsSection/PostsSection.js
  src/components/SearchBox/SearchBox.css
  src/components/SearchBox/SearchBox.js
  src/components/SpanMainPage/SpanMainPage.css
  src/components/SpanMainPage/SpanMainPage.js
  src/components/loginPage/LoginPage.js
  src/components/sidePanel/SidePanel.js
  src/imgs/Background.png
  src/imgs/girl.png
  src/imgs/groupchat.png
  src/imgs/lamp.png
  src/imgs/logo.svg
  src/imgs/manschool.png
  src/imgs/questionmark.png
  src/imgs/speechbubble.png
  src/index.css
  src/pages/homePage/Homepage.js
  src/pages/mainPage/MainPage.js
  src/pages/userPage/UserPage.js
Labels: enhancement

#13 Feature main page side panel rp
  src/App.css
  src/App.js
  src/components/PostsSection/PostsSection.js
  src/components/loginPage/LoginPage.js
  src/components/sidePanel/SidePanel.js
  src/components/sidePanel/SidePanelStyles.css
  src/imgs/Background.png
  src/imgs/logo.svg
  src/imgs/profiles/profile1.jpg
  src/imgs/profiles/profile2.jpg
  src/imgs/profiles/profile3.jpg
  src/imgs/profiles/profile4.jpg
  src/imgs/profiles/profile5.jpg
  src/imgs/weather/cloudy.png
  src/imgs/weather/cloudy_rain.png
  src/imgs/weather/rain.png
  src/imgs/weather/snow.png
  src/imgs/weather/snow_cloud.png
  src/imgs/weather/sunny.png
  src/imgs/weather/thunder.png
  src/index.css
  src/pages/homePage/Homepage.js
  src/pages/mainPage/MainPage.js
  src/pages/mainPage/MainPageStyles.css
  src/pages/userPage/UserPage.js
Labels: enhancement

#20 add all the main body files again
  src/components/Feed/Feed.css
  src/components/Feed/Feed.js
  src/components/MainBody/MainBody.css
  src/components/MainBody/MainBody.js
  src/components/NewPost/NewPost.css
  src/components/NewPost/NewPost.js
  src/components/PostCards/PostCard.css
  src/components/PostCards/PostCard.js
  src/components/SearchBox/SearchBox.css
  src/components/SearchBox/SearchBox.js
  src/components/SpanMainPage/SpanMainPage.css
  src/components/SpanMainPage/SpanMainPage.js
  src/imgs/fakeuser.png
  src/imgs/girl.png
  src/imgs/groupchat.png
  src/imgs/lamp.png
  src/imgs/manschool.png
  src/imgs/questionmark.png
  src/imgs/speechbubble.png
Labels: enhancement

#15 Feature side panel
  src/components/sidePanel/SidePanel.js
  src/components/sidePanel/SidePanelStyles.css
  src/imgs/profiles/profile1.jpg
  src/imgs/profiles/profile2.jpg
  src/imgs/profiles/profile3.jpg
  src/imgs/profiles/profile4.jpg
  src/imgs/profiles/profile5.jpg
  src/imgs/weather/cloudy.png
  src/imgs/weather/cloudy_rain.png
  src/imgs/weather/rain.png
  src/imgs/weather/snow.png
  src/imgs/weather/snow_cloud.png
  src/imgs/weather/sunny.png
  src/imgs/weather/thunder.png
  src/pages/mainPage/MainPage.js
  src/pages/mainPage/MainPageStyles.css
Labels: enhancement

#25 Feature routing setup rp
  src/App.js
  src/components/navigationBar/NavigationBar.js
  src/index.js
  src/pages/hospitalPage/HospitalPage.js
  src/pages/hospitalPage/HospitalPageStyles.css
  src/pages/mainPage/MainPage.js
  src/pages/schoolPage/SchoolPage.js
  src/pages/schoolPage/SchoolPageStyles.css
Labels: enhancement

#26 Feature routing
  src/App.js
  src/components/navigationBar/NavigationBar.js
  src/index.js
  src/pages/hospitalPage/HospitalPage.js
  src/pages/hospitalPage/HospitalPageStyles.css
  src/pages/mainPage/MainPage.js
  src/pages/schoolPage/SchoolPage.js
  src/pages/schoolPage/SchoolPageStyles.css
Labels: enhancement

#32 Create branch for login - token - cookie handling
  src/App.js
  src/components/navigationBar/NavigationBar.js
Labels: enhancement

#38 Feature main page
  src/components/SpanMainPage/SpanMainPage.css
Labels: enhancement

#42 Feature login token rp
  src/App.js
  src/common/index.js
  src/utils/posts/index.js
  src/utils/users/index.js
Labels: enhancement

#44 Feature homescreen
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/loginForm.css
  src/components/RegisterForm/RegisterForm.js
  src/components/RegisterForm/registerForm.css
  src/components/loginPage/LoginPage.js
  src/components/loginPage/LoginPageStyles.css
  src/pages/homePage/Homepage.js
Labels: enhancement

#43 Feature login
  src/App.js
  src/common/index.js
  src/utils/posts/index.js
  src/utils/users/index.js
Labels: enhancement

#49 Add routing fix for netlify
  public/_redirects
Labels: bug

#50 Extrapages mn
  .eslintrc.js
  src/App.js
  src/common/index.js
  src/components/AccountBody/AccountBody.js
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/loginForm.css
  src/components/MainBody/MainBody.js
  src/components/RegisterForm/RegisterForm.js
  src/components/RegisterForm/registerForm.css
  src/components/allAccountPage/AccountBody/AccountBody.css
  src/components/allAccountPage/AccountBody/AccountBody.js
  src/components/allAccountPage/SideAccount/SideAccount.css
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/components/allAccountPage/SpanAccount/SpanAccount.css
  src/components/allAccountPage/SpanAccount/SpanAccount.js
  src/components/allHospital/HospitalBody/HospitalBody.css
  src/components/allHospital/HospitalBody/HospitalBody.js
  src/components/allHospital/SpanHospital/SpanHospital.css
  src/components/allHospital/SpanHospital/SpanHospital.js
  src/components/allMainPage/MainBody/MainBody.css
  src/components/allMainPage/MainBody/MainBody.js
  src/components/allMainPage/NewPost/NewPost.css
  src/components/allMainPage/NewPost/NewPost.js
  src/components/allMainPage/SpanMainPage/SpanMainPage.css
  src/components/allMainPage/SpanMainPage/SpanMainPage.js
  src/components/allSchool/SchoolBody/SchoolBody.css
  src/components/allSchool/SchoolBody/SchoolBody.js
  src/components/allSchool/SpanSchool/SpanSchool.css
  src/components/allSchool/SpanSchool/SpanSchool.js
  src/components/allShared/Feed/Feed.css
  src/components/allShared/Feed/Feed.js
  src/components/allShared/InfoCards/InfoCards.css
  src/components/allShared/InfoCards/InfoCards.js
  src/components/allShared/PostCards/PostCard.css
  src/components/allShared/PostCards/PostCard.js
  src/components/allShared/SearchBox/SearchBox.css
  src/components/allShared/SearchBox/SearchBox.js
  src/components/loginPage/LoginPage.js
  src/components/loginPage/LoginPageStyles.css
  src/pages/homePage/Homepage.js
  src/pages/hospitalPage/HospitalPage.js
  src/pages/hospitalPage/HospitalPageStyles.css
  src/pages/mainPage/MainPage.js
  src/pages/schoolPage/SchoolPage.js
  src/pages/schoolPage/SchoolPageStyles.css
  src/pages/userPage/UserPage.js
  src/utils/posts/index.js
  src/utils/users/index.js
Labels: enhancement

#52 Feature extra pages
  .eslintrc.js
  src/components/AccountBody/AccountBody.js
  src/components/MainBody/MainBody.js
  src/components/allAccountPage/AccountBody/AccountBody.css
  src/components/allAccountPage/AccountBody/AccountBody.js
  src/components/allAccountPage/SideAccount/SideAccount.css
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/components/allAccountPage/SpanAccount/SpanAccount.css
  src/components/allAccountPage/SpanAccount/SpanAccount.js
  src/components/allHospital/HospitalBody/HospitalBody.css
  src/components/allHospital/HospitalBody/HospitalBody.js
  src/components/allHospital/SpanHospital/SpanHospital.css
  src/components/allHospital/SpanHospital/SpanHospital.js
  src/components/allMainPage/MainBody/MainBody.css
  src/components/allMainPage/MainBody/MainBody.js
  src/components/allMainPage/NewPost/NewPost.css
  src/components/allMainPage/NewPost/NewPost.js
  src/components/allMainPage/SpanMainPage/SpanMainPage.css
  src/components/allMainPage/SpanMainPage/SpanMainPage.js
  src/components/allSchool/SchoolBody/SchoolBody.css
  src/components/allSchool/SchoolBody/SchoolBody.js
  src/components/allSchool/SpanSchool/SpanSchool.css
  src/components/allSchool/SpanSchool/SpanSchool.js
  src/components/allShared/Feed/Feed.css
  src/components/allShared/Feed/Feed.js
  src/components/allShared/InfoCards/InfoCards.css
  src/components/allShared/InfoCards/InfoCards.js
  src/components/allShared/PostCards/PostCard.css
  src/components/allShared/PostCards/PostCard.js
  src/components/allShared/SearchBox/SearchBox.css
  src/components/allShared/SearchBox/SearchBox.js
  src/pages/hospitalPage/HospitalPage.js
  src/pages/hospitalPage/HospitalPageStyles.css
  src/pages/mainPage/MainPage.js
  src/pages/schoolPage/SchoolPage.js
  src/pages/schoolPage/SchoolPageStyles.css
  src/pages/userPage/UserPage.js
Labels: enhancement

#53 add modal to new message
  src/components/allMainPage/NewPost/NewPost.js
  src/components/allShared/MsgModal/MsgModal.css
  src/components/allShared/MsgModal/MsgModal.js
  src/components/navigationBar/NavigationBar.js
  src/components/navigationBar/NavigationBarStyles.css
  src/components/sidePanel/SidePanel.js
Labels: enhancement

#56 Feature extra pages
  src/components/allMainPage/NewPost/NewPost.js
  src/components/allShared/MsgModal/MsgModal.css
  src/components/allShared/MsgModal/MsgModal.js
  src/components/navigationBar/NavigationBar.js
  src/components/navigationBar/NavigationBarStyles.css
  src/components/sidePanel/SidePanel.js
Labels: enhancement

#55 Feature login
  public/_redirects
  src/App.js
  src/common/index.js
  src/components/LoginForm/LoginForm.js
  src/components/RegisterForm/RegisterForm.js
  src/components/allAccountPage/AccountBody/AccountBody.js
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/components/allAccountPage/SpanAccount/SpanAccount.js
  src/components/allMainPage/MainBody/MainBody.js
  src/components/allMainPage/SpanMainPage/SpanMainPage.js
  src/components/loginPage/LoginPage.js
  src/components/navigationBar/NavigationBar.js
  src/components/sidePanel/SidePanel.js
  src/pages/homePage/Homepage.js
  src/pages/mainPage/MainPage.js
  src/pages/userPage/UserPage.js
  src/utils/users/index.js
Labels: enhancement

#57 Adds bug fix for login and register
  src/components/loginPage/LoginPage.js
Labels: enhancement

#60 Feature routing authorisation
  .eslintrc.js
  .gitignore
  public/_redirects
  src/App.js
  src/common/index.js
  src/components/Feed/Feed.js
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/loginForm.css
  src/components/MainBody/MainBody.css
  src/components/MainBody/MainBody.js
  src/components/RegisterForm/RegisterForm.js
  src/components/RegisterForm/registerForm.css
  src/components/allAccountPage/AccountBody/AccountBody.css
  src/components/allAccountPage/AccountBody/AccountBody.js
  src/components/allAccountPage/SideAccount/SideAccount.css
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/components/allAccountPage/SpanAccount/SpanAccount.css
  src/components/allAccountPage/SpanAccount/SpanAccount.js
  src/components/allHospital/HospitalBody/HospitalBody.css
  src/components/allHospital/HospitalBody/HospitalBody.js
  src/components/allHospital/SpanHospital/SpanHospital.css
  src/components/allHospital/SpanHospital/SpanHospital.js
  src/components/allMainPage/MainBody/MainBody.css
  src/components/allMainPage/MainBody/MainBody.js
  src/components/allMainPage/NewPost/NewPost.css
  src/components/allMainPage/NewPost/NewPost.js
  src/components/allMainPage/SpanMainPage/SpanMainPage.css
  src/components/allMainPage/SpanMainPage/SpanMainPage.js
  src/components/allSchool/SchoolBody/SchoolBody.css
  src/components/allSchool/SchoolBody/SchoolBody.js
  src/components/allSchool/SpanSchool/SpanSchool.css
  src/components/allSchool/SpanSchool/SpanSchool.js
  src/components/allShared/Feed/Feed.css
  src/components/allShared/Feed/Feed.js
  src/components/allShared/InfoCards/InfoCards.css
  src/components/allShared/InfoCards/InfoCards.js
  src/components/allShared/MsgModal/MsgModal.css
  src/components/allShared/MsgModal/MsgModal.js
  src/components/allShared/PostCards/PostCard.css
  src/components/allShared/PostCards/PostCard.js
  src/components/allShared/SearchBox/SearchBox.css
  src/components/allShared/SearchBox/SearchBox.js
  src/components/loginPage/LoginPage.js
  src/components/loginPage/LoginPageStyles.css
  src/components/navigationBar/NavigationBar.js
  src/components/navigationBar/NavigationBarStyles.css
  src/components/sidePanel/SidePanel.js
  src/components/sidePanel/SidePanelStyles.css
  src/index.css
  src/pages/homePage/Homepage.js
  src/pages/hospitalPage/HospitalPage.js
  src/pages/hospitalPage/HospitalPageStyles.css
  src/pages/mainPage/MainPage.js
  src/pages/mainPage/MainPageStyles.css
  src/pages/schoolPage/SchoolPage.js
  src/pages/schoolPage/SchoolPageStyles.css
  src/pages/userPage/UserPage.js
  src/pages/userPage/UserPageStyles.css
  src/utils/posts/index.js
  src/utils/users/index.js
Labels: bug

#61 Feature routing
  src/App.js
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/pages/mainPage/MainPage.js
  src/pages/userPage/UserPage.js
  src/utils/users/index.js
Labels: bug

#62 Extrapages mn
  .gitignore
  public/_redirects
  src/App.js
  src/common/index.js
  src/components/LoginForm/LoginForm.js
  src/components/RegisterForm/RegisterForm.js
  src/components/allAccountPage/AccountBody/AccountBody.js
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/components/allAccountPage/SpanAccount/SpanAccount.js
  src/components/allMainPage/MainBody/MainBody.js
  src/components/allMainPage/SpanMainPage/SpanMainPage.js
  src/components/allSchool/SchoolBody/SchoolBody.js
  src/components/allShared/InfoCards/InfoCards.css
  src/components/allShared/InfoCards/InfoCards.js
  src/components/allShared/SearchBox/SearchBox.css
  src/components/loginPage/LoginPage.js
  src/components/navigationBar/NavigationBar.js
  src/components/navigationBar/NavigationBarStyles.css
  src/components/sidePanel/SidePanel.js
  src/imgs/medical.jpg
  src/imgs/schools.jpg
  src/imgs/user.png
  src/pages/homePage/Homepage.js
  src/pages/hospitalPage/HospitalPage.js
  src/pages/mainPage/MainPage.js
  src/pages/schoolPage/SchoolPage.js
  src/pages/userPage/UserPage.js
  src/utils/posts/index.js
  src/utils/schools/index.js
  src/utils/users/index.js
Labels: enhancement

#63 Feature extra pages
  src/App.js
  src/components/allSchool/SchoolBody/SchoolBody.js
  src/components/allShared/InfoCards/InfoCards.css
  src/components/allShared/InfoCards/InfoCards.js
  src/components/allShared/SearchBox/SearchBox.css
  src/components/navigationBar/NavigationBar.js
  src/components/navigationBar/NavigationBarStyles.css
  src/imgs/medical.jpg
  src/imgs/schools.jpg
  src/imgs/user.png
  src/pages/hospitalPage/HospitalPage.js
  src/pages/schoolPage/SchoolPage.js
  src/utils/schools/index.js
Labels: enhancement

#64 Extrapages mn
  src/App.js
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/components/sidePanel/SidePanel.js
  src/pages/mainPage/MainPage.js
  src/pages/schoolPage/SchoolPage.js
  src/pages/userPage/UserPage.js
  src/utils/users/index.js
Labels: enhancement

#67 Feature routing
  src/components/allAccountPage/SideAccount/SideAccount.js
Labels: bug

#68 Feature posts connection mr
  src/App.js
  src/components/allMainPage/MainBody/MainBody.js
  src/components/allMainPage/NewPost/NewPost.js
  src/components/allShared/MsgModal/MsgModal.js
  src/components/allShared/PostCards/PostCard.js
  src/components/navigationBar/NavigationBar.js
  src/pages/mainPage/MainPage.js
  src/pages/userPage/UserPage.js
  src/utils/posts/index.js
Labels: enhancement

#79 Feature routing
  src/App.js
  src/components/allSchool/SchoolBody/SchoolBody.js
  src/pages/mainPage/MainPage.js
  src/pages/schoolPage/SchoolPage.js
Labels: bug

#87 Extrapages mn
  src/App.js
  src/components/allAccountPage/SavedPostsCard/SavedPostsCard.css
  src/components/allAccountPage/SavedPostsCard/SavedPostsCard.js
  src/components/allAccountPage/SideAccount/SideAccount.css
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/components/allMainPage/NewPost/NewPost.css
  src/components/allMainPage/NewPost/NewPost.js
  src/components/allSchool/SchoolBody/SchoolBody.js
  src/components/allShared/MsgModal/MsgModal.js
  src/components/allShared/PostCards/PostCard.css
  src/components/allShared/PostCards/PostCard.js
  src/components/sidePanel/SidePanel.js
  src/components/sidePanel/SidePanelStyles.css
  src/imgs/profiles/profile10.jpg
  src/imgs/profiles/profile11.jpg
  src/imgs/profiles/profile12.jpg
  src/imgs/profiles/profile13.jpg
  src/imgs/profiles/profile14.jpg
  src/imgs/profiles/profile15.jpg
  src/imgs/profiles/profile6.jpg
  src/imgs/profiles/profile7.jpg
  src/imgs/profiles/profile8.jpg
  src/imgs/profiles/profile9.jpg
  src/pages/mainPage/MainPage.js
  src/pages/schoolPage/SchoolPage.js
Labels: enhancement

#85 Add posts are filtered and refresh when a new post is created
  src/App.js
  src/components/allMainPage/MainBody/MainBody.js
  src/components/allMainPage/NewPost/NewPost.js
  src/components/allShared/MsgModal/MsgModal.js
  src/components/navigationBar/NavigationBar.js
  src/pages/mainPage/MainPage.js
  src/utils/posts/index.js
Labels: enhancement

#88 Feature extra pages
  src/components/allAccountPage/SavedPostsCard/SavedPostsCard.css
  src/components/allAccountPage/SavedPostsCard/SavedPostsCard.js
  src/components/allAccountPage/SideAccount/SideAccount.css
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/components/allMainPage/NewPost/NewPost.css
  src/components/allMainPage/NewPost/NewPost.js
  src/components/allShared/MsgModal/MsgModal.js
  src/components/allShared/PostCards/PostCard.css
  src/components/allShared/PostCards/PostCard.js
  src/components/sidePanel/SidePanel.js
  src/components/sidePanel/SidePanelStyles.css
  src/imgs/profiles/profile10.jpg
  src/imgs/profiles/profile11.jpg
  src/imgs/profiles/profile12.jpg
  src/imgs/profiles/profile13.jpg
  src/imgs/profiles/profile14.jpg
  src/imgs/profiles/profile15.jpg
  src/imgs/profiles/profile6.jpg
  src/imgs/profiles/profile7.jpg
  src/imgs/profiles/profile8.jpg
  src/imgs/profiles/profile9.jpg
Labels: enhancement

#90 Feature postfeed
  src/App.js
  src/components/allMainPage/MainBody/MainBody.js
  src/components/allMainPage/NewPost/NewPost.js
  src/components/allShared/Feed/Feed.js
  src/components/allShared/MsgModal/MsgModal.js
  src/components/allShared/PostCards/PostCard.css
  src/components/allShared/PostCards/PostCard.js
  src/components/navigationBar/NavigationBar.js
  src/pages/mainPage/MainPage.js
  src/pages/userPage/UserPage.js
  src/utils/posts/index.js
Labels: enhancement

#91 add extra variable to the maxCharsValidation to fix bug with error msg
  src/components/allShared/MsgModal/MsgModal.js
Labels: bug

#95 fixed double likes and double favorites icons
  src/components/allMainPage/MainBody/MainBody.css
  src/components/allShared/PostCards/PostCard.css
  src/components/allShared/PostCards/PostCard.js
Labels: bug

#96 search implemented on main page
  src/components/allMainPage/MainBody/MainBody.js
  src/components/allShared/SearchBox/SearchBox.js
  src/utils/posts/index.js
Labels: enhancement

#97 post delete and edit only available for owned items
  src/components/allShared/PostCards/PostCard.js
  src/utils/posts/index.js
Labels: enhancement

#98 Feature extra pages hospitals rp
  src/App.js
  src/components/allHospital/HospitalBody/HospitalBody.js
  src/components/allHospital/SpanHospital/SpanHospital.js
  src/components/allMainPage/MainBody/MainBody.css
  src/components/allMainPage/MainBody/MainBody.js
  src/components/allMainPage/NewPost/NewPost.js
  src/components/allSchool/SchoolBody/SchoolBody.js
  src/components/allSchool/SpanSchool/SpanSchool.js
  src/components/allShared/Feed/Feed.js
  src/components/allShared/InfoCards/InfoCards.js
  src/components/allShared/MsgModal/MsgModal.js
  src/components/allShared/PostCards/PostCard.css
  src/components/allShared/PostCards/PostCard.js
  src/components/navigationBar/NavigationBar.js
  src/pages/hospitalPage/HospitalPage.js
  src/pages/mainPage/MainPage.js
  src/pages/userPage/UserPage.js
  src/utils/posts/index.js
Labels: enhancement

#100 Feature main page
  package-lock.json
  package.json
  src/App.js
  src/components/allMainPage/MainBody/MainBody.css
  src/components/allMainPage/MainBody/MainBody.js
  src/components/allShared/PostCards/PostCard.css
  src/components/allShared/PostCards/PostCard.js
Labels: enhancement

#102 Feature user page
  src/components/allAccountPage/AccountBody/AccountBody.js
  src/components/allMainPage/MainBody/MainBody.js
Labels: enhancement

#116 Feature postfeed
  src/App.js
  src/components/allAccountPage/AccountBody/AccountBody.js
  src/components/allMainPage/MainBody/MainBody.js
  src/components/allShared/Feed/Feed.js
  src/components/allShared/PostCards/PostCard.js
  src/components/allShared/SearchBox/SearchBox.js
  src/pages/mainPage/MainPage.js
  src/pages/userPage/UserPage.js
  src/utils/posts/index.js
Labels: enhancement

#117 Add bug fix
  package-lock.json
  src/components/allMainPage/MainBody/MainBody.js
Labels: bug

#121 Feature homescreen
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/loginForm.css
  src/components/RegisterForm/RegisterForm.js
  src/components/RegisterForm/registerForm.css
  src/components/loginPage/LoginPage.js
  src/components/loginPage/LoginPageStyles.css
Labels: enhancement

#126 fixes #107 loging and register panels can now be closed
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/loginForm.css
  src/components/RegisterForm/RegisterForm.js
Labels: enhancement

#127 fixes #106 logout now removes the jwt cookie
  src/components/navigationBar/NavigationBar.js
Labels: bug

#128 Feature extra pages
  src/App.js
  src/components/allHospital/HospitalBody/HospitalBody.js
  src/components/allHospital/SpanHospital/SpanHospital.js
  src/components/allSchool/SchoolBody/SchoolBody.js
  src/components/allSchool/SpanSchool/SpanSchool.js
  src/components/allShared/InfoCards/InfoCards.js
  src/pages/hospitalPage/HospitalPage.js
Labels: enhancement

#131 Feature postfeed user page favourite rp
  package-lock.json
  src/components/allAccountPage/AccountBody/AccountBody.js
  src/components/allAccountPage/SavedPosts/SavedPosts.css
  src/components/allAccountPage/SavedPosts/SavedPosts.js
  src/components/allAccountPage/SavedPostsCard/SavedPostsCard.css
  src/components/allAccountPage/SavedPostsCard/SavedPostsCard.js
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/components/allMainPage/MainBody/MainBody.js
  src/components/allShared/DelModal/DelModal.css
  src/components/allShared/DelModal/DelModal.js
  src/components/allShared/PostCards/PostCard.css
  src/components/allShared/PostCards/PostCard.js
  src/components/sidePanel/SidePanel.js
  src/pages/userPage/UserPage.js
  src/utils/posts/index.js
Labels: enhancement

#132 Dev issuefixes iw
  package-lock.json
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/loginForm.css
  src/components/RegisterForm/RegisterForm.js
  src/components/RegisterForm/registerForm.css
  src/components/navigationBar/NavigationBar.js
  src/utils/posts/index.js
  src/utils/users/index.js
Labels: bug

#136 feature-weather
  src/utils/weather/index.js
Labels: enhancement

#135 Write comments for hospitals
  src/utils/hospitals/index.js
Labels: enhancement

#141 Bug fix posts
  src/utils/posts/index.js
Labels: bug

#142 Changed envar
  src/utils/posts/index.js
Labels: bug

#144 Remove logs
  src/utils/posts/index.js
Labels: bug, enhancement

#145 Add api string
  src/utils/users/index.js
Labels: bug, enhancement

#140 #70 add checked for categories when creating a message and set defaul…
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  src/App.css
  src/components/allAccountPage/AccountBody/AccountBody.js
  src/components/allAccountPage/SavedPosts/SavedPosts.css
  src/components/allAccountPage/SavedPosts/SavedPosts.js
  src/components/allAccountPage/SavedPostsCard/SavedPostsCard.css
  src/components/allMainPage/MainBody/MainBody.js
  src/components/allShared/MsgModal/MsgModal.js
  src/components/allShared/PostCards/PostCard.css
  src/components/allShared/PostCards/PostCard.js
  src/index.css
Labels: bug

#147 API Bug fix
  src/utils/posts/index.js
Labels: bug

#153 Feature user page bugfix bombin rp
  package-lock.json
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  src/App.css
  src/App.js
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/loginForm.css
  src/components/RegisterForm/RegisterForm.js
  src/components/RegisterForm/registerForm.css
  src/components/allAccountPage/AccountBody/AccountBody.js
  src/components/allAccountPage/SavedPosts/SavedPosts.css
  src/components/allAccountPage/SavedPosts/SavedPosts.js
  src/components/allAccountPage/SavedPostsCard/SavedPostsCard.css
  src/components/allAccountPage/SavedPostsCard/SavedPostsCard.js
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/components/allHospital/HospitalBody/HospitalBody.js
  src/components/allHospital/SpanHospital/SpanHospital.js
  src/components/allMainPage/MainBody/MainBody.js
  src/components/allSchool/SchoolBody/SchoolBody.js
  src/components/allSchool/SpanSchool/SpanSchool.js
  src/components/allShared/DelModal/DelModal.css
  src/components/allShared/DelModal/DelModal.js
  src/components/allShared/Feed/Feed.js
  src/components/allShared/InfoCards/InfoCards.js
  src/components/allShared/MsgModal/MsgModal.js
  src/components/allShared/PostCards/PostCard.css
  src/components/allShared/PostCards/PostCard.js
  src/components/allShared/SearchBox/SearchBox.js
  src/components/loginPage/LoginPage.js
  src/components/loginPage/LoginPageStyles.css
  src/components/navigationBar/NavigationBar.js
  src/components/sidePanel/SidePanel.js
  src/index.css
  src/pages/hospitalPage/HospitalPage.js
  src/pages/mainPage/MainPage.js
  src/pages/userPage/UserPage.js
  src/utils/hospitals/index.js
  src/utils/posts/index.js
  src/utils/users/index.js
  src/utils/weather/index.js
Labels: bug

#154 Feature user page
  src/components/allAccountPage/AccountBody/AccountBody.js
  src/components/allAccountPage/SavedPosts/SavedPosts.js
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/pages/userPage/UserPage.js
Labels: bug

#155 Weather mn
  src/components/sidePanel/SidePanel.js
  src/components/sidePanel/SidePanelStyles.css
  src/imgs/weather/cloudy.png
  src/imgs/weather/cloudy_rain.png
  src/imgs/weather/rain.png
  src/imgs/weather/snow.png
  src/imgs/weather/snow_cloud.png
  src/imgs/weather/sunny.png
  src/imgs/weather/thunder.png
Labels: enhancement

#159 Responsivepage mn
  src/components/LoginForm/loginForm.css
  src/components/RegisterForm/registerForm.css
  src/components/allAccountPage/AccountBody/AccountBody.js
  src/components/allAccountPage/SavedPosts/SavedPosts.css
  src/components/allAccountPage/SavedPosts/SavedPosts.js
  src/components/allAccountPage/SavedPostsCard/SavedPostsCard.css
  src/components/allAccountPage/SideAccount/SideAccount.css
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/components/allMainPage/NewPost/NewPost.css
  src/components/allMainPage/NewPost/NewPost.js
  src/components/allShared/DelModal/DelModal.css
  src/components/allShared/DelModal/DelModal.js
  src/components/allShared/MsgModal/MsgModal.css
  src/components/allShared/SearchBox/SearchBox.css
  src/components/loginPage/LoginPageStyles.css
  src/components/navigationBar/NavigationBar.js
  src/components/navigationBar/NavigationBarStyles.css
  src/pages/mainPage/MainPageStyles.css
  src/pages/userPage/UserPage.js
  src/pages/userPage/UserPageStyles.css
Labels: enhancement

#160 Feature main page
  src/components/LoginForm/loginForm.css
  src/components/RegisterForm/registerForm.css
  src/components/allAccountPage/AccountBody/AccountBody.js
  src/components/allAccountPage/SavedPosts/SavedPosts.css
  src/components/allAccountPage/SavedPostsCard/SavedPostsCard.css
  src/components/allAccountPage/SideAccount/SideAccount.css
  src/components/allMainPage/NewPost/NewPost.css
  src/components/allMainPage/NewPost/NewPost.js
  src/components/allShared/DelModal/DelModal.css
  src/components/allShared/DelModal/DelModal.js
  src/components/allShared/MsgModal/MsgModal.css
  src/components/allShared/SearchBox/SearchBox.css
  src/components/loginPage/LoginPageStyles.css
  src/components/navigationBar/NavigationBar.js
  src/components/navigationBar/NavigationBarStyles.css
  src/pages/mainPage/MainPageStyles.css
  src/pages/userPage/UserPageStyles.css
Labels: enhancement

#161 Bug fix data back
  src/components/allAccountPage/SavedPosts/SavedPosts.js
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/components/allShared/PostCards/PostCard.css
  src/components/allShared/PostCards/PostCard.js
  src/components/sidePanel/SidePanel.js
  src/components/sidePanel/SidePanelStyles.css
  src/imgs/weather/cloudy.png
  src/imgs/weather/cloudy_rain.png
  src/imgs/weather/rain.png
  src/imgs/weather/snow.png
  src/imgs/weather/snow_cloud.png
  src/imgs/weather/sunny.png
  src/imgs/weather/thunder.png
  src/utils/users/index.js
Labels: bug

#162 Feature user page
  src/components/allAccountPage/SavedPosts/SavedPosts.js
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/utils/users/index.js
Labels: bug

#165 change localdatestring to en-gb
  src/components/sidePanel/SidePanel.js
Labels: bug

#166 add visibility hidden to the edit icon and fixed the comments share span
  src/components/allShared/PostCards/PostCard.css
  src/components/allShared/PostCards/PostCard.js
Labels: bug

#184 fixes #171 add a condition to only show the saved post if there is a …
  examples/useInfoModel.js
  src/components/allAccountPage/SavedPostsCard/SavedPostsCard.js
Labels: bug

#182 Feature hospitals apicall mr
  package-lock.json
  src/components/allHospital/HospitalBody/HospitalBody.js
  src/pages/hospitalPage/HospitalPage.js
  src/utils/hospitals/index.js
  src/utils/weather/index.js
Labels: enhancement

#185 Weatherjs mn
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/App.css
  src/components/LoginForm/loginForm.css
  src/components/RegisterForm/registerForm.css
  src/components/allAccountPage/AccountBody/AccountBody.js
  src/components/allAccountPage/SavedPosts/SavedPosts.css
  src/components/allAccountPage/SavedPosts/SavedPosts.js
  src/components/allAccountPage/SavedPostsCard/SavedPostsCard.css
  src/components/allAccountPage/SavedPostsCard/SavedPostsCard.js
  src/components/allAccountPage/SideAccount/SideAccount.css
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/components/allAccountPage/SpanAccount/SpanAccount.css
  src/components/allAccountPage/SpanAccount/SpanAccount.js
  src/components/allHospital/SpanHospital/SpanHospital.css
  src/components/allHospital/SpanHospital/SpanHospital.js
  src/components/allMainPage/MainBody/MainBody.js
  src/components/allMainPage/NewPost/NewPost.css
  src/components/allMainPage/NewPost/NewPost.js
  src/components/allSchool/SchoolBody/SchoolBody.js
  src/components/allSchool/SpanSchool/SpanSchool.css
  src/components/allSchool/SpanSchool/SpanSchool.js
  src/components/allShared/DelModal/DelModal.css
  src/components/allShared/DelModal/DelModal.js
  src/components/allShared/MsgModal/MsgModal.css
  src/components/allShared/MsgModal/MsgModal.js
  src/components/allShared/PostCards/PostCard.css
  src/components/allShared/PostCards/PostCard.js
  src/components/allShared/SearchBox/SearchBox.css
  src/components/loginPage/LoginPageStyles.css
  src/components/navigationBar/NavigationBar.js
  src/components/navigationBar/NavigationBarStyles.css
  src/components/sidePanel/SidePanel.js
  src/components/sidePanel/SidePanelStyles.css
  src/imgs/weather/cloudy.png
  src/imgs/weather/cloudy_rain.png
  src/imgs/weather/rain.png
  src/imgs/weather/snow.png
  src/imgs/weather/snow_cloud.png
  src/imgs/weather/sunny.png
  src/imgs/weather/thunder.png
  src/index.css
  src/pages/hospitalPage/HospitalPage.js
  src/pages/mainPage/MainPage.js
  src/pages/mainPage/MainPageStyles.css
  src/pages/schoolPage/SchoolPage.js
  src/pages/userPage/UserPage.js
  src/pages/userPage/UserPageStyles.css
  src/utils/comments/index.js
  src/utils/hospitals/index.js
  src/utils/posts/index.js
  src/utils/users/index.js
  src/utils/weather/index.js
Labels: enhancement

#186 Feature hospitals
  package-lock.json
  src/components/allHospital/HospitalBody/HospitalBody.js
  src/pages/hospitalPage/HospitalPage.js
  src/utils/hospitals/index.js
Labels: enhancement

#192 Dev
  .gitignore
  examples/useInfoModel.js
  package-lock.json
  public/index.html
  src/components/LoginForm/loginForm.css
  src/components/RegisterForm/registerForm.css
  src/components/allAccountPage/AccountBody/AccountBody.js
  src/components/allAccountPage/SavedPosts/SavedPosts.css
  src/components/allAccountPage/SavedPosts/SavedPosts.js
  src/components/allAccountPage/SavedPostsCard/SavedPostsCard.css
  src/components/allAccountPage/SavedPostsCard/SavedPostsCard.js
  src/components/allAccountPage/SideAccount/SideAccount.css
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/components/allAccountPage/SpanAccount/SpanAccount.css
  src/components/allAccountPage/SpanAccount/SpanAccount.js
  src/components/allHospital/HospitalBody/HospitalBody.js
  src/components/allHospital/SpanHospital/SpanHospital.css
  src/components/allHospital/SpanHospital/SpanHospital.js
  src/components/allMainPage/NewPost/NewPost.css
  src/components/allMainPage/NewPost/NewPost.js
  src/components/allSchool/SchoolBody/SchoolBody.js
  src/components/allSchool/SpanSchool/SpanSchool.css
  src/components/allSchool/SpanSchool/SpanSchool.js
  src/components/allShared/DelModal/DelModal.css
  src/components/allShared/DelModal/DelModal.js
  src/components/allShared/InfoModal/InfoModal.css
  src/components/allShared/InfoModal/InfoModal.js
  src/components/allShared/MsgModal/MsgModal.css
  src/components/allShared/MsgModal/MsgModal.js
  src/components/allShared/PostCards/PostCard.css
  src/components/allShared/PostCards/PostCard.js
  src/components/allShared/SearchBox/SearchBox.css
  src/components/loginPage/LoginPageStyles.css
  src/components/navigationBar/NavigationBar.js
  src/components/navigationBar/NavigationBarStyles.css
  src/components/sidePanel/SidePanel.js
  src/components/sidePanel/SidePanelStyles.css
  src/imgs/weather/cloudy.png
  src/imgs/weather/cloudy_rain.png
  src/imgs/weather/rain.png
  src/imgs/weather/snow.png
  src/imgs/weather/snow_cloud.png
  src/imgs/weather/sunny.png
  src/imgs/weather/thunder.png
  src/pages/hospitalPage/HospitalPage.js
  src/pages/mainPage/MainPage.js
  src/pages/mainPage/MainPageStyles.css
  src/pages/schoolPage/SchoolPage.js
  src/pages/userPage/UserPage.js
  src/pages/userPage/UserPageStyles.css
  src/utils/comments/index.js
  src/utils/hospitals/index.js
  src/utils/users/index.js
  src/utils/weather/index.js
Labels: enhancement

#195 Bugfix mn
  src/components/allAccountPage/SavedPosts/SavedPosts.css
  src/components/allAccountPage/SavedPosts/SavedPosts.js
  src/components/allAccountPage/SideAccount/SideAccount.css
  src/components/allHospital/HospitalBody/HospitalBody.css
  src/components/allHospital/HospitalBody/HospitalBody.js
  src/components/allShared/InfoModal/InfoModal.css
  src/components/allShared/InfoModal/InfoModal.js
  src/components/allShared/SearchBox/SearchBox.css
  src/components/allShared/SearchBox/SearchBox.js
  src/components/navigationBar/NavigationBarStyles.css
  src/pages/hospitalPage/HospitalPage.js
  src/pages/userPage/UserPageStyles.css
  src/utils/hospitals/index.js
Labels: bug

#198 fixes #122 add user search own post feature
  src/components/allAccountPage/AccountBody/AccountBody.js
  src/utils/posts/index.js
Labels: enhancement

#205 Change p tag to link
  src/components/allShared/InfoCardsHospital/InfoCardsHospital.js
Labels: enhancement

#207 fix hospital contact links
  src/components/allShared/InfoCardsHospital/InfoCardsHospital.js
Labels: bug

#208 Lastcss mn
  src/components/allHospital/HospitalBody/HospitalBody.css
  src/components/allHospital/HospitalBody/HospitalBody.js
  src/components/allShared/InfoCards/InfoCards.css
  src/components/allShared/InfoCardsHospital/InfoCardsHospital.css
  src/components/allShared/InfoCardsHospital/InfoCardsHospital.js
Labels: bug

#211 Dev
  src/common/index.js
  src/components/allAccountPage/AccountBody/AccountBody.js
  src/components/allAccountPage/SavedPosts/SavedPosts.css
  src/components/allAccountPage/SavedPosts/SavedPosts.js
  src/components/allAccountPage/SavedPostsCard/SavedPostsCard.js
  src/components/allAccountPage/SideAccount/SideAccount.css
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/components/allHospital/HospitalBody/HospitalBody.css
  src/components/allHospital/HospitalBody/HospitalBody.js
  src/components/allMainPage/SpanMainPage/SpanMainPage.js
  src/components/allShared/InYourRegion/InYourRegion.css
  src/components/allShared/InYourRegion/InYourRegion.js
  src/components/allShared/InfoCards/InfoCards.css
  src/components/allShared/InfoCardsHospital/InfoCardsHospital.css
  src/components/allShared/InfoCardsHospital/InfoCardsHospital.js
  src/components/allShared/InfoModal/InfoModal.css
  src/components/allShared/InfoModal/InfoModal.js
  src/components/allShared/MsgModal/MsgModal.js
  src/components/allShared/PostCards/PostCard.js
  src/components/allShared/SearchBox/SearchBox.css
  src/components/allShared/SearchBox/SearchBox.js
  src/components/navigationBar/NavigationBar.js
  src/components/navigationBar/NavigationBarStyles.css
  src/components/sidePanel/SidePanel.js
  src/components/sidePanel/SidePanelStyles.css
  src/index.css
  src/pages/hospitalPage/HospitalPage.js
  src/pages/userPage/UserPageStyles.css
  src/utils/comments/index.js
  src/utils/hospitals/index.js
  src/utils/posts/index.js
  src/utils/schools/index.js
  src/utils/users/index.js
  src/utils/weather/index.js
Labels: enhancement

#213 Bugfix mn
  src/components/allAccountPage/SavedPosts/SavedPosts.js
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/components/allHospital/HospitalBody/HospitalBody.js
  src/components/allShared/InYourRegion/InYourRegion.css
  src/components/navigationBar/NavigationBar.js
  src/components/sidePanel/SidePanel.js
  src/components/sidePanel/SidePanelStyles.css
Labels: bug

#215 Dev
  src/components/allAccountPage/SavedPosts/SavedPosts.js
  src/components/allAccountPage/SideAccount/SideAccount.js
  src/components/allHospital/HospitalBody/HospitalBody.js
  src/components/allShared/InYourRegion/InYourRegion.css
  src/components/allShared/InYourRegion/InYourRegion.js
  src/components/navigationBar/NavigationBar.js
  src/components/sidePanel/SidePanel.js
  src/components/sidePanel/SidePanelStyles.css
Labels: bug
